baseURL: 'https://insightic.io'
languageCode: 'en-us'
title: 'Insightic - Web3 Compliance Made Easy'
theme: 'theme'

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  # Offices that are shown in the contact us page
  offices:
    - country: Singapore
      map: /public/img/insightic-singapore.png
      address: '#01-16, 75 Ayer Rajah Crescent Singapore 139953'
      phone: +65 9000 0000
      email: info@insightic.io
    - country: Singapore
      map: /public/img/insightic-singapore.png
      address: '#01-16, 75 Ayer Rajah Crescent Singapore 139953'
      phone: +65 9000 0000
      email: info@insightic.io

  # Founding Members that are shown in the about page
  foundingMembers:
    - name: Shengliang Lu
      avatar: /img/about/shengliang.jpeg
      title: Chief Executive Officer
    - name: Bingsheng He
      avatar: /img/about/bingsheng.jpg
      title: Chief Scientist

  # Team Members that are shown in the about page
  teamMembers:
    - name: 'imwithye.eth'
      avatar: /img/about/imwithye.png
      title: Lead Developer
    - name: Jason Ng
      avatar: /img/about/jason.jpeg
      title: Fullstack Software Developer
    - name: Boon Chong Peh
      avatar: /img/about/boon-chong.jpeg
      title: Backend Developer
    - name: Zhi Yong Ong
      avatar: /img/about/zhiyong.jpeg
      title: CMO
    - name: Xiaofan Huang
      avatar: /img/about/xiaofan.jpeg
      title: Marketing Executive (Internship)
    - name: Yuzhu Zou
      avatar: /img/about/yuzhu.jpeg
      title: Marketing Executive (Internship)
